{{- if .Values.writeEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dbagent-probe.fullname" . }}-write
  labels:
    {{- include "dbagent-probe.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["patch", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dbagent-probe.fullname" . }}-write
  labels:
    {{- include "dbagent-probe.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dbagent-probe.fullname" . }}-write
subjects:
  - kind: ServiceAccount
    name: {{ include "dbagent-probe.fullname" . }}
{{- end }}
