apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rca-probe.fullname" . }}-state
  labels:
    {{- include "rca-probe.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.state.storageClass }}
  storageClassName: {{ .Values.state.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.state.size }}
